# Use an official Python runtime as the base image
FROM ubuntu:22.04

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY zip.py .

# Run the Python script when the container starts
CMD ["python", "zip.py"]
