# Use an official Python runtime as the base image
FROM ubuntu

RUN apt-get update
RUN apt-get install -y python3 python-is-python3

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY zip.py .

# Run the Python script when the container starts
CMD ["python", "zip.py"]
